### PR TITLE
Propose a contributing.md file

### PR DESCRIPTION
**Pull request by manuphatak**
Hey, I took notes from setting up the repo. 

The setup is pretty simple!  But still, I thought it'd be nice to write it down -- especially the time zone thing.

### CODE REVIEW

**Comment by nicolashefti** [comment]
I am a bit surprised regarding the time zone setting. The library should not be tied to any timezone in particular.

I tried `TZ='Asia/Calcutta' node_modules/.bin/mocha` and things are still working. Or did I miss something?

**Comment by manuphatak** [comment]
I created a bug report here:  #85

**Comment by nicolashefti** [comment]
@manuphatak I just merged a PR fixing the time zone issue. Can you test it on your side? We could close this PR.

**Comment by manuphatak** [comment]
@nicolashefti Yup!  Everything works!  Right out of the box ... I tried `npm install` and `npm test`  and got passing tests!

image


Nice work 👍  We're good to close this PR

**Pull request closed without merging**
