### PR TITLE
Fix SUMIFS: Specifications did not match documentation 

### PR DESCRIPTION
**Pull request by luc-freyermuth**
The tests did not match the documentation nor the excel documentation I can find. As a result, the functions appears to be broken.

Screenshot from 2020-12-28 03-32-52

I tried to fix the specs and the implementation but I don't know the lib well, maybe there was a better way to do it :)

### CODE REVIEW

**Comment by nicolashefti** [comment]
@luc-freyermuth thanks for the PR. It looks pretty good. I'll review the code this week and let you know.

Are you using [this page ](https://support.microsoft.com/en-us/office/sumifs-function-c9e748f5-7ea7-455d-9406-611cebce642b)as Excel doc reference?

**Comment by luc-freyermuth** [comment]
Hi @nicolashefti :) Yes that's what I was using as reference for Excel !

**Comment by nicolashefti** [comment]
@luc-freyermuth sorry about the delay, it's on my ToDo of the week...

**Review by nicolashefti — APPROVED** [review]
Looks good to me. Thanks for your contribution.

**Pull request merged**
