### PR TITLE
Add type definitions

### PR DESCRIPTION
**Pull request by bornova**
One thing missing from this repo is some type definitions.  Currently, when used in an IDE, no Intellisense or autocomplete hints are provided.  This PR adds definitions based on official Microsoft Excel documentation found here: https://support.microsoft.com/en-us/office/excel-functions-alphabetical-b3944572-255d-4efb-bb96-c6d90033e188

Screen Shot 2022-07-04 at 8 46 31 PM
Screen Shot 2022-07-04 at 8 44 34 PM

Some things to note:
- This is not actually for checking types but mostly to provide Intellisense providers the data needed to suggest autocompletions and suggestions in IDE's.  For this reason, initially all parameter types are of value `any` (`@param {*}`)
- All parameters of exported functions have been updated to match the official Excel documentation. Ex:
    Old: 
    ```javascript
    export function IF(test, then_value, otherwise_value) { ... }
    ```
    New:
    ```javascript
    export function IF(logical_test, value_if_true, value_if_false) { ... }
    ```
- All data was pulled automatically from above link, so further cleanup may be needed.
- No breaking changes.  All functionality remains the same.

I thought this would make the user experience closer to Excel and hope this is a good starting point.  Let me know if this something the team would like to implement.

### CODE REVIEW

**Comment by nicolashefti** [comment]
Thanks @bornova. I like the overall idea.

## Types
Can you add the script to generate the index.d.ts to package.json, so we can update it in the future?

## Function inputs naming
Good initiative to make the experience more fluid between Excel and Formula.js

## JDocs
That would be good to add them but this is a lot of work. Maybe we should start with one file (logical.js) as an exemple and implement the rest "on the flow" while we fix bugs and/or implement new functions.

**Comment by bornova** [comment]
Hi @nicolashefti, thanks for taking a look!
- Automatically generating types using the typescript tool at the source level generates multiple d.ts files. One for each `import` in `src/index.js` since this is the entry point.  However, we could build the library first and then auto generate using the `lib/esm/index.mjs` file as entry point.  But then the resulting file would be `index.d.mts` not `.ts`. This second method is what I used to make the `index.d.ts`, I just renamed the extension to `.ts`.  Also, when I generated the types automatically, there was an error with `FLOOR.PRECISE` definition.  The tool for some reason outputs `import PRECISE = MATH` where `MATH` is not defined.  I had to manually fix it to `import PRECISE = FLOOR.MATH`
- So basically I ran into some issues with the typescript tool.  FYI, after installing typescript globally, the CLI command I used is this:  `tsc lib/esm/index.mjs --declaration --allowJs --emitDeclarationOnly --outDir types`
- As for JSDocs, I had initially included them in each file already (see my initial commit on the branch). The `index.d.ts` file then was generated from these comments.  But I later removed all JSDoc comments from each file thinking it will be easier to maintain just one `index.d.ts` file and avoid duplicate entries.

I am open to suggestions ans improvements!  I will look deeper into how we can automate the `.d.ts` generation.  Like you mentioned, maybe the best approach is to keep the JSDoc comments in the source files and then auto generate the `index.d.ts`

**Comment by bornova** [comment]
- I was able to find the issue with `FLOOR.PRECISE`.  Changing `FLOOR.PRECISE = FLOOR.MATH` to `FLOOR.PRECISE = FLOOR['MATH']` solved the issue.
- I have added back JSDoc comments to source files so typescript can use them to generate `.d.ts` files.
- Added `types` script to `package.json`.  We can now do `npm run types` and types will be automatically generated.
- All type definition files will go inside `types` folder.  This folder is ignored in Github but is generated during build step and will be published with the library.

**Comment by nicolashefti** [comment]
@bornova nice work. Looks very good. Sorry about my late reply. This is ready on your side?

Out of curiosity, how did you pull all the parameter defitions for the JSDoc? Did you scrap Microsoft website manually?

**Comment by bornova** [comment]
@nicolashefti Manually getting all the parameters and definitions would have taken too much time and effort so I wrote small a scraping script to pull all the data from Microsoft.  But I did manually go thru each function to review the data. 

It is mostly ready to go but I found a few discrepancies which I would like to fix before merging if you agree:

`FINDFIELD()`:  This is a helper function for Formula.js only in database.js.  It's not an Excel function.  Therefore should be lowercase and not exported.

Incorrect categories (Current > New):
`CHOOSE()`: Logical > Lookup and reference
`CEILING()`: Math and trig > Compatibility - MS says category should be Compatibility but I think it should stay as Math and trig to stay consistent with `CEILING.MATH()` and `CEILING.PRECISE()`
`FLOOR()`: Math and trig > Compatibility - Same situation as `CEILING()`
`UNIQUE()`: Miscellaneous > Lookup and reference
`COLUMN()`: Statistical > Lookup and reference
`COLUMNS()`: Statistical > Lookup and reference
`NORM.INV()`: Statistical > Compatibility - MS says category should be Compatibility but should stay in Statistical
`ROWS()`: Statistical > Lookup and reference
`TRANSPOSE()`: Statistical > Lookup and reference

I know this is a lot of change for one PR but I think we can implement all in one shot since changes are all related and take care of any future fixes and improvements with new PRs. What do you think?

**Review by bornova — COMMENTED** [review]
I had initially removed the `FINDFIELD` function since it's not an Excel function, however, in order to avoid breaking changes, decided to add it back.  There are also other non-Excel functions in the library but the discussion to remove them or not can continue here: #79

**Comment by bornova** [comment]
Hi @nicolashefti,
Any thoughts on this?  I also would like to start a PR to fix #46 and it would make it cleaner if this was merged first. Thanks!

**Review by nicolashefti — APPROVED** [review]

**Pull request merged**
