### PR TITLE
Replace `should` with `chai`

### PR DESCRIPTION
**Pull request by bornova**
[should.js](https://github.com/shouldjs/should.js) is officially dead as of Nov 8, 2022.  I propose we move to [chai](https://github.com/chaijs/chai) instead.

All test cases remain the same but syntax would be different.  Instead of writing:
```javascript
(formula(a, b)).should.equal(c)
```
we would write:
```javascript
expect(formula(a, b)).to.equal(c)
```
`chai.js` does allow the use of `should` as well but I found it to be a bit buggy with some of our test cases.  `expect` assertion style seems to be a bit more robust.  However, this is open to discussion.  More info [here](https://www.chaijs.com/guide/styles/).

### CODE REVIEW

**Comment by andraz** [comment]
I asked ChatGPT to give an informed opinion of using Jest:

| Feature | Chai | Jest |
|---------|------|------|
| Assertion library | Yes | No |
| Testing framework | No | Yes |
| Browser support | Yes | No |
| Node.js support | Yes | Yes |
| Asynchronous testing support | Yes | Yes |
| Mocking support | Yes | Yes |
| Spy support | Yes | Yes |
| Coverage reporting | Yes | Yes |

Chai is an assertion library, which means it provides a set of functions for making assertions about the behavior of your code. It does not provide a testing framework, so you will need to use it in conjunction with a separate testing tool.

Jest is a full-featured testing framework that includes support for assertions, as well as tools for mocking, spying, and coverage reporting. It is designed specifically for testing JavaScript code, and it can be used in Node.js or in a command-line interface.

Chai can be used in both the browser and Node.js, while Jest is only compatible with Node.js.

Both Chai and Jest support asynchronous testing and provide tools for mocking and spying. However, only Jest includes built-in coverage reporting.

Overall, the main differences between Chai and Jest are that Chai is an assertion library and Jest is a testing framework, and Jest has additional features like coverage reporting that Chai does not provide.

**Comment by bornova** [comment]
Hi @andraz!
Thanks for the detailed comparison.  Amazing how far AI has come!  I looked at Jest as well.  It is definitely a viable option.  I just thought since we already use Mocha, Chai would be a more natural switch.  The syntax is somewhat familiar and most of our contributors seems to be ok with it.

Also, one thing to note is that Jest currently ships with [experimental support for ECMAScript Modules (ESM](https://jestjs.io/docs/ecmascript-modules)).

**Comment by nicolashefti** [comment]
Hi @bornova @andraz 

My pros:
 
1) Agreed with @bornova, given the current setup, Chai looks like the natural choice.

2) Now @bornova did the work to remove `should`, I would go for it.

Cons:

3) This PR is a breaking changes for all other opened PR. I'm not sure there is a hurry to replace `should`

And beyond:

4) Jest seems to be a more all-in-tool test framework that goes beyond what we have, especially with code coverage. It would be interesting to know more about grey zones of the library. If someone wants to propose a PR with Jest and maybe one test file migration to get the feeling of it, I'm open to it.

**Comment by bornova** [comment]
Thanks for the feedback @nicolashefti
Point 3 is a valid one.  I can help convert the test cases there if needed.

**Review by nicolashefti — APPROVED** [review]

**Comment by nicolashefti** [comment]
@bornova @andraz I moved on and merged the PR. All other open PRs need some rework. The changes related `chai` are quite easy to handle given the test syntax is very similar. Have a nice weekend!

**Pull request merged**
