### PR TITLE
Partially created TEXT formula

### PR DESCRIPTION
**Pull request by Kyle1297**
Partially implemented for decimals, percentages, general numbers, some currency formats, plus maybe a few more.

The following are not supported:
 - Scientific notation
 - Leading and trailing zeros
 - Some special formats like "[<=9999999]###-####;(###) ###-####", "###° 00' 00''"
 - Fractions
 - Dates and times
 - Some accounting formats
 - Thousands separator

I did created associated test cases for the above though. Right now, they are just commented out. Should be easy to pick up later on.

Linked issue is here: https://github.com/formulajs/formulajs/issues/117

Excel reference: https://support.microsoft.com/en-us/office/text-function-20d5ac4d-7b94-49fd-bb38-93d29371225c

Sample Excel sheet of some test cases:
[TEXT function examples.xlsx](https://github.com/formulajs/formulajs/files/10182081/TEXT.function.examples.xlsx)

### CODE REVIEW

**Comment by nicolashefti** [comment]
Thanks @Kyle1297 

I like the idea of partial implementation. We had a similar approach with VALUE.

Two general remarks:
1) Why do we need an additional dependency (Decimal.js)? This is a browser library and adding a dependency just for one formula seems overkill to me. Any possibility to find a workaround?

2) Code style and comments. I would rather go for something like

```
xit('should work with fraction',() =>{
  // Failling test cases here
});
```
 instead of commenting partially on some of the test cases you identified. What do you think?

@bornova , any thoughts on these 2 points?

**Comment by Kyle1297** [comment]
> Why do we need an additional dependency (Decimal.js)? This is a browser library and adding a dependency just for one formula seems overkill to me. Any possibility to find a workaround?

It just makes it very easy to handle javascript's weird handling of floating numbers, e.g.:
```
> 4.32 + 4.78
9.100000000000001
```

DecimalJS converts this to: `9.1` instead.

It's also a tiny package, shouldn't really affect anything, right? I am sure other functions can use it as well?

**Comment by nicolashefti** [comment]
@Kyle1297 I just opened the discussion outside the PR #126. Feel free to comment on it.

**Comment by nicolashefti** [comment]
Hi @Kyle1297, I merged another contribution (#130) with DOLLAR, FIXED and also TEXT. It's a bit more compact than yours and without new dependency.

Can you check if it covers the test cases you wrote?

**Pull request closed without merging**
