### PR TITLE
Bug/fix export of `T.` functions

### PR DESCRIPTION
**Pull request by bornova**
Currently, re-exporting of `T` function in index.js doesn't seem to work as intended.  It seems to override all the statistical functions.  Therefore, functions such as `T.DIST` or `T.INV` are not available in the bundle.  This PR fixes this by adding statistical methods to original `T` text function and re-exporting `T` with these methods.

### CODE REVIEW

**Comment by nicolashefti** [comment]
@bornova sorry about the late review. I might have missed a point. I'm not sure to understand what's the aim.

In browser mode (using the DevTools on this page https://formulajs.info/functions/), I can:

```
TINV(0.9946953263673741, 1)
> 59.99999999996536
T.INV(0.9946953263673741, 1)
> 59.99999999996536
T('hello')
> "hello" 
```

**Comment by bornova** [comment]
Hi @nicolashefti,
https://formulajs.info/functions/ seems to use an older version of formulas (2.9.3).  If you try the same examples with the newest version, `TINV` works, but methods with dot notation will throw error: `Uncaught TypeError: formulajs.T.INV is not a function`.

**Comment by nicolashefti** [comment]
Good time to update the website... So the PR fixes this, the way if used to be around 2.9.x?

**Comment by bornova** [comment]
Yes.  Not sure if this is the best way to do it, but it does resolve the issue.

We may also want to look for a way to test the bundles after building, since current tests use each function at module level and therefore does not catch issues like this.

**Review by nicolashefti — APPROVED** [review]

**Pull request merged**
